version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tasktracker
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data


  adminer:
    image: adminer
    restart: always
    ports:
      - "8083:8080"
    depends_on:
      - db

volumes:
  postgres-data: